version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

workflows:
  build-and-test:
    jobs:
      - cypress/run:
          install-command: npm install
          cypress-command: npx cypress run


